### PR TITLE
Parse taxonomy file to dataframe

### LINKED ISSUE #14: Parse taxonomy files to a tidy format

### PR DESCRIPTION
**Pull request by NLesniak**
Resolves #14

### CODE REVIEW

**Review by kelly-sovacool — CHANGES_REQUESTED** [review]
Thanks for opening the PR! A few thoughts:
1. It's good practice to reference the issue number that this PR resolves in the PR description or in one of the commits, so the issue will be automatically closed once this gets merged (e.g resolves #14). I renamed this PR title to resemble that issue.
1. tidyr's  `gather()` and `spread()` have been superseded by `pivot_longer()` and `pivot_wider()`. Can you use those instead?
1. I think many of the inline comments that simply describe what the code does aren't necessary.
1. What do you think about renaming this function to something like `read_taxonomy()` or `read_tax()` so it matches `read_dist()`? We might even decide to re-organize these functions that read files into a file called "readers".
1. Maybe we should come up with smaller test files so we don't have to compare only the head & tail? I know I did this with `read_dist()` too. It would be cleaner to be able to compare the entire object that the function returns. I could see potential for missed bugs by only comparing parts of the output. Any ideas for how we would make smaller but still valid output files from mothur?

**Comment by kelly-sovacool** [comment]
@NLesniak if you take a look at the details of the `build` or `test-coverage` checks, you can see the test for this function failed. Probably because the example taxonomy file isn't in `inst/extdata/`?

**Comment by NLesniak** [comment]
@kelly-sovacool  thanks for the feedback, I wasn't immediately sure what the error messages meant but once I went back to implement the suggestions you made I noticed I did not have the example file tracked.

**Comment by NLesniak** [comment]
@kelly-sovacool  edits incorporated and test passed!

**Review by kelly-sovacool — APPROVED** [review]
Looks great, it's ready to be merged!

**Pull request merged**
